Repository BitBotFactory/MikaLendingBot, pull requests merged in 2018-03, with the labels that each got.

#615 using abspath for resolving template path
  modules/WebServer.py
Labels: In Progress, Queued

#616 Add no response bot
  .github/no-response.yml
Labels: Enhancement, Testing Phase

#603 [FIX/UPDATE] Setting permissions and commands
  docs/installation.rst
Labels: Testing Phase

#618 Fix off by one error
  modules/Lending.py
Labels: Bug, Testing Phase

#617 Add DNS cache
  .gitignore
  lendingbot.py
Labels: Enhancement, Testing Phase

#621 Only display charts for active currencies
  plugins/Charts.py
Labels: Queued
